relf/egobox

- Cargo.toml
- README.md
- ego/Cargo.toml
- ego/src/egor.rs
- ego/src/mixint.rs
- ego/src/mixintegor.rs
- ego/src/utils.rs
- gp/Cargo.toml
- gp/src/lib.rs
- moe/Cargo.toml
- moe/examples/clustering.rs
- moe/examples/moe_norm1.rs
- moe/examples/norm1.rs
- moe/src/algorithm.rs
- moe/src/clustering.rs
- moe/src/errors.rs
- moe/src/expertise_macros.rs
- moe/src/gaussian_mixture.rs
- moe/src/lib.rs
- moe/src/parameters.rs
- moe/src/surrogates.rs
- src/lib.rs
> MoE improvements

- doe/src/lib.rs
- ego/src/egor.rs
- ego/src/errors.rs
- ego/src/lib.rs
- ego/src/mixint.rs
- ego/src/mixintegor.rs
- ego/src/types.rs
- gp/src/correlation_models.rs
- gp/src/lib.rs
- gp/src/mean_models.rs
- src/lib.rs
> Refactor MixintEgor

- Dockerfile
- openssl.pc
Dockerfile to get manylinux maturin image with LLVM and generate `egobox` Python module on Linux
> egobox on linux

- ego/src/egor.rs
- ego/src/lhs_optimizer.rs
- ego/src/lib.rs
- ego/src/types.rs
This PR mitigates problems coming from next selected point too close to previous ones by falling back to LHS optimization to explore other part of the design space and improving surrogate modeling.
> Ego: Add LHS optimization

- ego/src/egor.rs
- src/lib.rs
This PR fixes a bug in qEI strategy logic: gp models of objective and constraints were not updated correctly.
> Fix qEI strategy handling

- .github/workflows/pytest.yml
- Cargo.toml
- README.md
- doe/Cargo.toml
- ego/Cargo.toml
- ego/src/egor.rs
- ego/src/lhs_optimizer.rs
- ego/src/mixint.rs
- ego/src/mixintegor.rs
- ego/src/utils.rs
- gp/Cargo.toml
- moe/Cargo.toml
- moe/src/algorithm.rs
- moe/src/clustering.rs
- moe/src/parameters.rs
- pyproject.toml
- python/egobox/tests/test_egor.py
- src/lib.rs
> Release 0.4.0

- Cargo.toml
- ego/Cargo.toml
- moe/Cargo.toml
- moe/benches/bench_find_nb_clusters.rs
- moe/src/clustering.rs
> Improve clustering

- Cargo.toml
- ego/src/egor.rs
- ego/src/lhs_optimizer.rs
- ego/src/mixintegor.rs
- moe/src/algorithm.rs
- src/lib.rs
Implement interruption on Ctrl+C
> Egor interrupt

- .github/workflows/test.yml
- README.md
- gp/src/algorithm.rs
Make two versions (blas and non-blas) of `reduced_likelihood` as stated in #33
> Refactor reduced_likelihood

- src/lib.rs
Address [this part](https://github.com/relf/egobox/issues/35#issuecomment-1242802809) of #35
> Add links to sub-crates in egobox module doc

- ego/src/egor.rs
- ego/src/mixint.rs
- ego/src/types.rs
- gp/src/algorithm.rs
- moe/src/algorithm.rs
- moe/src/surrogates.rs
This PR to address the first two points of #33
> API improvements 

- ego/src/egor.rs
- gp/src/algorithm.rs
- moe/examples/moe_norm1.rs
- moe/src/algorithm.rs
- moe/src/clustering.rs
- moe/src/gaussian_mixture.rs
- moe/src/surrogates.rs
Address [this part](https://github.com/relf/egobox/issues/35#issuecomment-1242801774) of #35
> Write test files in target/tests dir

- CHANGELOG.md
- Cargo.toml
- doe/Cargo.toml
- ego/Cargo.toml
- ego/src/egor.rs
- gp/Cargo.toml
- moe/Cargo.toml
- pyproject.toml
* #34 
* #36 
* #38 
* #39 
* #40 
* #42
> Release 0.5.0

- ego/src/egor.rs
- gp/Cargo.toml
- gp/src/algorithm.rs
- gp/src/correlation_models.rs
- moe/src/expertise_macros.rs
Implement derivatives for quadratic regression
> Quadratic regression derivatives

- ego/src/mixintegor.rs
- gp/src/algorithm.rs
- gp/src/correlation_models.rs
- gp/src/utils.rs
- python/egobox/tests/test_egor.py
Implement the derivatives of the absolute exponential correlation model
> Absolute exponential derivatives

- gp/src/algorithm.rs
- gp/src/correlation_models.rs
- gp/src/utils.rs
This PR implements Matern32 and Matern52 jacobian computation
> Matern kernel derivatives

- Cargo.toml
- doe/Cargo.toml
- ego/Cargo.toml
- gp/Cargo.toml
- moe/Cargo.toml
* Bump `linfa` to 0.6.1
* Bump `ndarray-linalg` to 0.15
* Remove `anyhow` version restriction
> Upgrade dependencies

- ego/src/egor.rs
- gp/src/algorithm.rs
- gp/src/correlation_models.rs
- gp/src/mean_models.rs
- moe/src/clustering.rs
Factorize and optimize some computations
> Refactor correlation models

- gp/src/algorithm.rs
- gp/src/correlation_models.rs
- gp/src/mean_models.rs
- moe/src/algorithm.rs
Reactivate variance derivatives tests
> Test variance derivatives

- ego/Cargo.toml
- ego/src/criteria/ei.rs
- ego/src/criteria/mod.rs
- ego/src/criteria/wb2.rs
- ego/src/egor.rs
- ego/src/egor_solver.rs
- ego/src/lib.rs
- ego/src/utils.rs
This PR refactors infill criterion as a trait-object for code maintainability and extensibility.
> Make the infill criterion a trait

- ego/src/mixint.rs
- python/egobox/tests/test_sampling.py
- src/egor.rs
- src/lib.rs
- src/sampling.rs
> Make mixed-integer sampling methods available in Python

- Cargo.toml
- doe/Cargo.toml
- ego/Cargo.toml
- gp/Cargo.toml
- moe/Cargo.toml
- pyproject.toml
> Upgrade edition 2021

- gp/src/sgp_algorithm.rs
- gp/src/sgp_parameters.rs
* Pass inducings at constructor time
* Make `Inducings` on exhaustive
> Rework SGP API

- Cargo.toml
- doe/benches/lhs.rs
- doe/src/lhs.rs
- doe/src/utils.rs
- ego/Cargo.toml
- moe/src/gp_algorithm.rs
This PR improves optimized LHS execution time by removing some allocations. Benchmarks shows a 1.25x speedup.
> Improve optimized LHS performance

- .gitignore
- doe/benches/lhs.rs
- doe/benches/lhs_classics.rs
- doe/src/lhs.rs
- python/egobox/tests/test_mixintegor.py
The best LHS wrt points distance was not returned. This PR fixes this bug.
> Fix LHS maximin bug

- gp/src/algorithm.rs
- moe/src/algorithm.rs
- moe/src/gaussian_mixture.rs
- moe/src/parameters.rs
- python/egobox/tests/test_gpmix.py
- src/gp_mix.rs
In addition now hard recombination is enabled by default
> Fix GP mixture with kpls option on Griewank test function

- gp/src/algorithm.rs
- gp/src/lib.rs
- gp/src/optimization.rs
- gp/src/parameters.rs
- gp/src/sparse_algorithm.rs
- gp/src/sparse_parameters.rs
- moe/src/parameters.rs
- src/gp_mix.rs
- src/sparse_gp_mix.rs
This PR contains the following API refactoring:
* GP parameters: 
* `ParamTuning`  is removed
* `ThetaTuning` is now an enum
* Sparse GP paramaters:
* `ParamEstimation` is now `ParamTuning`
> Allow fixed hyperparameters theta for GP and Sparse GP

- ego/examples/mopta08.rs
- ego/src/egor.rs
- ego/src/egor_solver.rs
- gp/src/parameters.rs
* Add iteration timing
* Cap nb of points used for computing scalers
> Adjust log messages

- ego/src/egor.rs
- ego/src/egor_service.rs
- ego/src/egor_solver.rs
- ego/src/mixint.rs
- gp/src/algorithm.rs
- gp/src/parameters.rs
- gp/src/sparse_algorithm.rs
- gp/src/sparse_parameters.rs
- moe/src/algorithm.rs
- moe/src/parameters.rs
... also remove useless generecity of random number generator in `moe::GpMixtureParamds`
> Save original parameters in fitted gp models 

- ego/src/egor.rs
- ego/src/egor_solver.rs
- ego/src/egor_state.rs
- ego/src/mixint.rs
- gp/src/algorithm.rs
- gp/src/correlation_models.rs
- gp/src/lib.rs
- gp/src/metrics.rs
- gp/src/parameters.rs
- gp/src/sparse_algorithm.rs
- gp/src/sparse_parameters.rs
- gp/src/utils.rs
- moe/src/algorithm.rs
- moe/src/expertise_macros.rs
- moe/src/surrogates.rs
This PR introduces the `gp::CrossValScore` trait implemented by GaussianProcess, SparseGaussianProcess, GpMixture and and MixintGpMixture
> Implement cross validation metric

- ego/examples/ackley.rs
- ego/src/criteria/ei.rs
- ego/src/criteria/mod.rs
- ego/src/criteria/wb2.rs
- ego/src/solver/egor_impl.rs
- ego/src/solver/egor_solver.rs
- ego/src/solver/egor_state.rs
- ego/src/solver/trego.rs
- python/egobox/tests/test_egor.py
This PR fixes bug in WB2S scaling and fmin computation.
> Fix WB2S criteria scaling factor and fmin computation

- ego/src/egor.rs
- ego/src/solver/egor_impl.rs
- ego/src/solver/egor_solver.rs
- ego/src/solver/trego.rs
> Move the DOE save after the algo the iteration

- ego/src/egor.rs
- ego/src/lib.rs
- ego/src/solver/egor_config.rs
- ego/src/utils/hot_start.rs
- src/egor.rs
Use an enum instead of an option
> Improve hot start API

- doc/Egor_Tutorial.ipynb
- python/egobox/examples/optim_g24.py
@unkcpz, thanks for the heads up!
> Fix Python example optim g24

- crates/ego/src/solver/egor_config.rs
- crates/ego/src/solver/mod.rs
- crates/ego/src/solver/solver_computations.rs
- crates/ego/src/solver/solver_impl.rs
- crates/ego/src/types.rs
- python/egobox/egobox.pyi
- python/egobox/tests/test_egor.py
- python/src/egor.rs
- python/src/lib.rs
- python/src/types.rs
Now we can choose to manage metamodelized constraint using upper trust bound instead of mean value.
> Implement upper trusted bound criterion for constraint handling

- README.md
- crates/ego/examples/xsinx.rs
- crates/gp/examples/kriging.rs
- crates/gp/examples/kriging_xsinx.rs
> Add Rust simple examples

- README.md
- crates/doe/src/full_factorial.rs
- crates/ego/src/egor.rs
- crates/ego/src/lib.rs
- crates/ego/src/optimizers/gbnm/internal.rs
- crates/ego/src/solver/egor_solver.rs
- crates/ego/src/utils/hot_start.rs
> Refactor checkpoint and history file save

- doc/README.md
> Add link to an example of EGObox optimizer usage (MDO course 2025)

- crates/ego/examples/ackley.rs
- crates/ego/src/criteria/ei.rs
- crates/ego/src/egor.rs
- crates/ego/src/solver/solver_impl.rs
- crates/ego/src/solver/solver_infill_optim.rs
- crates/ego/src/utils/cstr_pof.rs
- crates/ego/src/utils/logei_helper.rs
- crates/ego/src/utils/mod.rs
- python/egobox/egobox.pyi
- python/egobox/tests/test_egor.py
- python/src/egor.rs
Use formulation from this [paper](https://openreview.net/pdf?id=1vyAG6j9PE)
Unfortunatly still cannot reproduce the results of the paper! Even worse, this LogEI does not seem to be any better than EI 😭
Tried also to use botorch implementation but without success 😞 I just reproduce my bad results, so...
Hopefully someday will found what I am doing wrong 😅
> Improve LogEI criterion computation  

- crates/ego/src/solver/coego.rs
- crates/ego/src/solver/egor_solver.rs
- crates/ego/src/solver/egor_state.rs
- crates/ego/src/solver/solver_computations.rs
- crates/ego/src/solver/solver_impl.rs
- crates/ego/src/solver/solver_infill_optim.rs
- crates/ego/src/solver/trego.rs
- crates/ego/src/types.rs
- crates/ego/src/utils/find_result.rs
This PR adjusts the infill criterion to use the probability of feasibility instead of the specified infill criterion till a feasible point is found.
> Use proba of feasibility criterion while no feasible point is found

- Cargo.lock
- crates/ego/Cargo.toml
- crates/ego/src/criteria/ei.rs
- crates/ego/src/criteria/mod.rs
- crates/ego/src/criteria/wb2.rs
- crates/ego/src/egor.rs
- crates/ego/src/solver/egor_solver.rs
- crates/ego/src/solver/solver_computations.rs
- crates/ego/src/solver/solver_impl.rs
- crates/ego/src/solver/solver_infill_optim.rs
- crates/ego/src/types.rs
- crates/ego/src/utils/mod.rs
- crates/ego/src/utils/portfolio.rs
This PR implements a portfolio strategy by D. Jones to get several promising points and mitigate erroneous GP variance.
This feature is experimental and gated by the environmental variable `EGOBOX_USE_GP_VAR_PORTFOLIO`
> Implement experimental gp variance weighting portfolio
