relf/egobox

- Cargo.toml
- README.md
- gp/Cargo.toml
- gp/src/algorithm.rs
- gp/src/correlation_models.rs
- gp/src/lib.rs
- gp/src/mean_models.rs
- gp/src/utils.rs
- moe/Cargo.toml
Now using gp, if serialization (`serde`) is required the feature `serializable` has to be enabled
> Make serialization optional in gp

- ego/src/egor.rs
- ego/src/lib.rs
- ego/src/mixint.rs
- ego/src/mixintegor.rs
- ego/src/types.rs
- gp/src/correlation_models.rs
- gp/src/mean_models.rs
- moe/src/algorithm.rs
- moe/src/clustering.rs
- moe/src/parameters.rs
- src/lib.rs
> Refactor ego/moe relation

- .github/workflows/test.yml
- Cargo.toml
- doe/Cargo.toml
- ego/Cargo.toml
- ego/src/egor.rs
- ego/src/lhs_optimizer.rs
- ego/src/lib.rs
- ego/src/mixintegor.rs
- gp/Cargo.toml
- gp/src/algorithm.rs
- gp/src/errors.rs
- moe/Cargo.toml
- moe/src/algorithm.rs
- moe/src/clustering.rs
- moe/src/errors.rs
- moe/src/gaussian_mixture.rs
- python/egobox/tests/test_egor.py
With the release of `linfa 0.6.0`, the depency on a BLAS library can be make optional. `linfa` can be linked with dedicated linear algebra library namely `linfa-linalg`. This PR makes `egobox` depends on `linfa-linalg` and keep build based on `ndarray-linalg` an option.
> Make BLAS dependency optional

- ego/src/egor.rs
- ego/src/lib.rs
- ego/src/mixint.rs
- ego/src/mixintegor.rs
- ego/src/types.rs
- ego/src/utils.rs
- moe/src/algorithm.rs
- moe/src/clustering.rs
- moe/src/gaussian_mixture.rs
- moe/src/lib.rs
- moe/src/surrogates.rs
- python/egobox/tests/test_egor.py
- src/lib.rs
Use MoE auto-clustering to implement automatic reclustering during optimization.
When number of clusters is set to 0 in Egor constructor, MoE models are clustered automatically initially and after every 10-points addition.
> Implement automatic reclustering

- doe/src/lhs.rs
- ego/examples/mopta08.rs
- ego/src/egor_solver.rs
- ego/src/lhs_optimizer.rs
- ego/src/types.rs
- ego/src/utils.rs
This PR introduces the parallel executions of infill criterion optimizations (multistart).
It also fixes several bugs related to criterion optimization:
* `cstr_tol` is now used by infill criterion optimization
* infill criterion is now scaled with correct value
* successive samplings with same LHS are now different
> Parallel multistart optimizations

- ego/examples/ackley.rs
- ego/examples/mopta08.rs
- ego/examples/rosenbrock.rs
- ego/src/egor_solver.rs
- ego/src/egor_state.rs
- ego/src/lib.rs
- gp/src/algorithm.rs
- gp/src/parameters.rs
- python/egobox/tests/test_egor.py
- python/egobox/tests/test_mixintegor.py
- src/egor.rs
Use more commonly used, the number of iterations instead of the number of evaluation of th function under optimization. More over this last number is not always accurate depending on the problem when `q_points` > 1.
This PR contains the following breaking changes:
*  `n_eval` is replaced by `n_iter`,
* `q_parallel` is replaced by `q_points` corresponding to the number of points to be evaluated by iteration (actually as some points may be rejected 1 < nb points <= q_points)
So finally we have    `n_doe` + `n_iter` <= `n_eval` <=  `n_doe` + `n_iter` * `q_points`
> Number of evaluations rework

- ego/examples/mopta08.rs
- ego/src/egor.rs
- ego/src/egor_solver.rs
- ego/src/lib.rs
- src/egor.rs
- src/gpmix.rs
This PR change `Egor` and `EgorSolver` API configuration methods taking an option:
* `outdir`
* `kpls_dim`
* `doe`
* `n_clusters`
Most of the time, those options are set once or not at all so using an `Option` was a bit awkward. Nevertheless, except for the last an `no_<option>()` was added to the API to allow unsetting the option if needed.
> Improve option api

- doc/Egor_Tutorial.ipynb
- ego/src/egor.rs
- ego/src/egor_solver.rs
- ego/src/egor_state.rs
- ego/src/mixint.rs
- ego/src/types.rs
- gp/benches/gp.rs
- gp/src/algorithm.rs
- moe/src/surrogates.rs
- python/egobox/tests/test_mixintegor.py
- src/egor.rs
- src/types.rs
This PR extends the continuous relaxation for ordered and enumaration variables at Python level.
Example of new declaration:
```
xtypes = [
egx.XSpec(egx.XType(egx.XType.FLOAT), [-5.0, 5.0]),                   # a float in [-5, 5]
egx.XSpec(egx.XType(egx.XType.ENUM), tags=["blue", "red", "green"]),  # 0, 1 or 2
egx.XSpec(egx.XType(egx.XType.ENUM), xlimits=[2]),                    # 0 or 1 
egx.XSpec(egx.XType(egx.XType.ORD), [0, 2.5, 3]),                     # 0, 2.5 or 3
]
egor = egx.Egor(mixobj, xtypes, seed=42)
res = egor.minimize(n_iter=10)
```
where `mixobj` is an objective function taking [[Float, Enum1, Enum2, Ord]] as inputs where Enum values are integer in 0, 1, ... enum-size.
This PR contains also a bug fix when first iter after doe is the best iter, it is not picked due to bad …
> Extend mixed-integer Py wrapper to ordered and enumeration variables

- ego/src/egor.rs
- ego/src/egor_config.rs
- ego/src/egor_service.rs
- ego/src/egor_solver.rs
- ego/src/lhs_optimizer.rs
- ego/src/mixint.rs
- ego/src/types.rs
- ego/src/utils.rs
This PR fixes `suggest()` method in order to accept DOE data input data and provide x suggestion in discrete space. 
It also fixes bugs and awkward API related to `xlimits` vs `xtypes` for discrete optimization:
* Remove wrong LHS optimisation parallel execution when rng is set (same point was drawn! Should be reworked)
* Fix `unfold_with enum_mask` indices bug
* EgorSolver constructor with xlimits is removed, hence new accepts xtypes now
* Clean up API `Egor`, `EgorService`, `EgorConfig`
* Improve error messages and comments in mixed-integer context.
> Fix Egor service in presence of discrete variables

- CHANGELOG.md
- CONTRIBUTING.md
- doe/src/lhs.rs
- ego/README.md
- ego/src/mixint.rs
- python/egobox/tests/test_sampling.py
- src/sampling.rs
that is the classic, maximin, centered, centered maximin beside the optimized one which stays the default
> Add Python bindings for all LHS flavours

- .github/workflows/test.yml
- Cargo.toml
- ego/Cargo.toml
- ego/src/criteria/ei.rs
- ego/src/criteria/mod.rs
- ego/src/criteria/wb2.rs
- ego/src/egor_solver.rs
- ego/src/mixint.rs
- ego/src/types.rs
- ego/src/utils.rs
- gp/src/algorithm.rs
- gp/src/sparse_algorithm.rs
- gp/src/sparse_parameters.rs
- moe/src/gp_algorithm.rs
- moe/src/sgp_algorithm.rs
- moe/src/sgp_parameters.rs
- moe/src/surrogates.rs
- moe/src/types.rs
- python/egobox/tests/test_gpmix.py
- src/gp_mix.rs
A `Gpx` mixture surrogate gives now access to hyperparameters `thetas`, `variances` and reduced `likelihood` value of the expert Gp surrogates resulting from the training process.
Some surrogate traits where refactored: 
* Add `GpSurrogateExt` trait to manage derivatives and sampling
* Add `GpParameterized` trait to manage optimized parameters
* `MixtureGpSurrogate` is not a `FullGpSurrogate` any more
* Add experts retrieval from `GpMixture`
> Add Gpx accessors

- Cargo.toml
- README.md
- doe/Cargo.toml
- ego/Cargo.toml
- gp/Cargo.toml
- moe/Cargo.toml
- pyproject.toml
- python/egobox/tests/test_egor.py
Bump version after renaming `predict_derivatives` as `predict_gradients`
> Prepare release 0.18

- ego/src/egor.rs
- ego/src/egor_config.rs
- ego/src/egor_solver.rs
- ego/src/egor_state.rs
- ego/src/mixint.rs
- ego/src/types.rs
- gp/src/algorithm.rs
- gp/src/parameters.rs
- gp/src/sparse_algorithm.rs
- moe/src/algorithm.rs
- moe/src/parameters.rs
- python/egobox/tests/test_egor.py
- src/gp_mix.rs
- src/sparse_gp_mix.rs
This PR leverages on #155 allowing to specify a rate of optimization for theta hyperparameters vi `n_optmod` option (1 means always, 2 means one out of 2, 3 means one out of 3, etc.).
> [EGO] Allow to reuse surrogate trainings (reuse previous hyperparameters) from a previous iteration

- ego/Cargo.toml
- ego/benches/ego.rs
- ego/examples/g24.rs
- ego/src/egor.rs
- ego/src/egor_config.rs
- ego/src/egor_service.rs
- ego/src/egor_solver.rs
- ego/src/egor_state.rs
- ego/src/lib.rs
- ego/src/types.rs
- gp/src/utils.rs
- src/egor.rs
This PR compute current best result from the previous one instead of comparing with the whole history.
Additionally `EgorConfig::random_seed()` is renamed `EgorConfig::seed()` **breaking change**
> Better Egor solver state handling

- ego/src/egor.rs
- ego/src/solver/egor_solver.rs
- python/egobox/tests/test_egor.py
The DOE_INITIAL_FILE is removed as the initial doe points are specified with an iteration number set to 0.
The .npy DOE file format has rows like : `n_iter, x, y` where `y` is `obj, cstr1, ..., cstr_n`.
Fixes #186
> Save iteration number

- ego/src/egor.rs
- ego/src/solver/egor_solver.rs
This PR saves the config used by the solver and the optimization history for subsequent analysis.
The following files are saved only if `outdir` potion is set
* `egor_config.json`: `EgorConfig` srtucture seriallized as json
* `egor_history`: numpy 2d-array each row being [obj, cstrs, params] value at a given iteration (row index)
> Save config and optim history

- ego/examples/mopta08.rs
- ego/src/egor.rs
- ego/src/lib.rs
- ego/src/solver/egor_config.rs
- ego/src/solver/egor_solver.rs
- ego/src/types.rs
- python/egobox/tests/test_egor.py
- src/egor.rs
Renaming badly named hot start which is more a warm start (as hot start would be using the checkpointing feature of argmin) and x_hist and y_hist in result are used for DOE, hist/history refers to costs, cstrs, params history file.
> Renaming `hotstart` option and `hist` fields of optimization result

- python/egobox/tests/test_gpmix.py
- src/gp_mix.rs
These are required in the context of a model loaded from file where we want to check input dim or even retrain another model with the same training data.
This PR adds the following getters to `Gpx` object:
* `dims()`: which returns input and output dimensions
* `training_data()`: which returns the nt training data points (x, y) used to fit the model
> Add training infos getters at Python level

- .gitignore
- ego/Cargo.toml
- ego/src/egor.rs
- ego/src/lib.rs
- ego/src/solver/egor_config.rs
- ego/src/solver/egor_impl.rs
- ego/src/solver/egor_service.rs
- ego/src/solver/egor_solver.rs
- ego/src/solver/egor_state.rs
- ego/src/solver/trego.rs
- ego/src/utils/hot_start.rs
- ego/src/utils/mod.rs
- src/egor.rs
This PR adds the ability to restart from previous saved iteration (checkpoint) either to complete to the max nb of iterations after an interruption or even to continue the optimization for an extended number of iterations after max_iters is reached.
This behaviour is controlled by the `hot_start` integer parameter which has to be set at least to 0 to enable the checkpointing and optionally set to n_iters > 0 to trigger n_iters iterations after `max_iters` is reached.
> Add checkpointing and hot start

- ego/src/egor.rs
- ego/src/solver/egor_config.rs
To be aligned with Python binding default
> Do not activate TREGO by default

- Cargo.lock
- Cargo.toml
Update to numpy crate 0.22.1 to fix win32 compilation
> Update to numpy crate 0.22.1 to fix win32 compilation

- gp/src/algorithm.rs
- gp/src/sparse_algorithm.rs
- python/egobox/tests/test_gpmix.py
- python/egobox/tests/test_sgpmix.py
The GaussianProcess/SparsegGaussianProcess current fit API accepts a training output being a 2D array but the model implementations actually handle only one dimensional output (ie training output has to be a column vector). 
Passing multiple output data leads to wrong predictors. 
As a short-term measure, to enforce this constraint, this PR adds the check of the training output dimension and panic if it is not a column vector.
This comes from original Python SMT API (see https://github.com/SMTorg/smt/issues/679) but actually should be revised in Rust. GP/SGP API should use an `Array1` as the type for training outputs (instead of an `Array2`).
> Panic if training output data is not one-dimensional

- crates/ego/examples/mopta08.rs
- crates/ego/src/egor.rs
- crates/ego/src/gpmix/mixint.rs
- crates/ego/src/gpmix/mod.rs
- crates/ego/src/solver/egor_config.rs
- crates/ego/src/solver/egor_impl.rs
- crates/ego/src/types.rs
- crates/moe/examples/clustering.rs
- crates/moe/examples/moe_norm1.rs
- crates/moe/examples/norm1.rs
- crates/moe/src/algorithm.rs
- crates/moe/src/clustering.rs
- crates/moe/src/lib.rs
- crates/moe/src/parameters.rs
- python/egobox/egobox.pyi
- python/src/egor.rs
- python/src/gp_mix.rs
Number of points in clusters is now checked wrt regression spec. See `check_number_of_points()`
This PR refactors the type to specify clustering specification: either defined by the user or automatically computed. See `NbClusters` type. Now when determined automatically a max number of clusters can be specified to shorten execution time.
Python binding: The `n_clusters` argument can take negative values `-n` to specify that the number of clusters tested is in [1, n].
This PR relates to #243
> Relax number of points required wrt regression spec

- crates/ego/examples/mopta08.rs
- crates/ego/examples/rosenbrock_hidim.rs
- crates/ego/src/egor.rs
- crates/ego/src/solver/coego.rs
- crates/ego/src/solver/egor_config.rs
- crates/ego/src/solver/egor_solver.rs
- crates/ego/src/solver/egor_state.rs
- crates/ego/src/solver/solver_computations.rs
- crates/ego/src/solver/solver_impl.rs
- crates/ego/src/solver/trego.rs
- crates/ego/src/utils/find_result.rs
- crates/moe/src/algorithm.rs
- crates/moe/src/lib.rs
- python/egobox/egobox.pyi
- python/egobox/tests/test_egor.py
- python/pyproject.toml
- python/src/egor.rs
- python/src/lib.rs
- python/src/types.rs
- python/uv.lock
Make CoEGO available:
* Rust: `EgorConfig.coego(CoegoStatus::Enabled(n_coop))` where n_coop is the number of components set
* Python: `Egor(coego_n_coop=n_coop)`
But also include some breaking changes foir naming consistency: 
* Rename `n_optmod` option in `q_optmod`
* Rename `par_infill_strategy` option in `q_infill_strategy`
* Rename `ParInfillStrategy` type in  `QInfillStrategy`
* Refactor EGO `compute_best_point` and TREGO `local_step` to prepare code factorization
> CoEGO implementation and refactoring

- .gitignore
- crates/doe/src/lhs.rs
- crates/doe/src/random.rs
- crates/ego/src/egor.rs
- crates/ego/src/optimizers/lhs_optimizer.rs
- crates/ego/src/solver/coego.rs
- crates/ego/src/solver/egor_service.rs
- crates/ego/src/solver/egor_solver.rs
- crates/ego/src/solver/egor_state.rs
- crates/ego/src/solver/mod.rs
- crates/ego/src/solver/solver_computations.rs
- crates/ego/src/solver/solver_impl.rs
- crates/ego/src/solver/solver_infill_optim.rs
- crates/ego/src/solver/trego.rs
This PR factorizes code between TREGO and EGO iteration algorithm using a common new `optimize_infill_criterion` method replacing `compute_best_point` in EGO and `local_step` in TREGO.
Moreover EgorSolver API is simplified using config `seed` instead of `rng`. 
Trait bound `Clone` is removed from `Random` sampling protecting Rng access (to be consistent with LHS sampling).
> Refactor infill criterion optimization

- crates/ego/src/egor.rs
- crates/ego/src/optimizers/gbnm/internal.rs
- crates/ego/src/optimizers/gbnm/mod.rs
- crates/ego/src/optimizers/mod.rs
- crates/ego/src/optimizers/optimizer.rs
- crates/ego/src/solver/solver_infill_optim.rs
- crates/ego/src/types.rs
- crates/moe/src/algorithm.rs
- python/src/egor.rs
- python/src/types.rs
This PR introduces the implementation of the Global Bounded Nelder-Mead algorithm as a new infill optimizer as described in [this paper](https://www.emse.fr/~leriche/gbnm_cas.pdf). 
This implementation in Rust is a transpilation of the Matlab found [here](https://github.com/ojdo/gbnm).
This algorithm can be activated with:
* Python: `egx.Egor(infill_optimizer=egx.InfillOptimizer.GBNM)`
* Rust: `EgorBuilder::optimize(...).configure(|cfg| cfg.infill_optimizer(InfillOptimizer::Gbnm))`
> Add a new Global Bounded Nelder-Mead infill criterion optimizer 

- crates/ego/src/egor.rs
- crates/ego/src/solver/coego.rs
Before when for instance x dimension is 124 and coego n_coop sets to 5, the activity matrix ends up being 6 x 24 with last row containing only 4 active components (ie 5 x 24 + 4 = 124). 
With this PR the activity matrix will be 5 x 25 with 24 active components in the last row (ie 4x25 + 24). It makes also the `n_coop` parameter truly the number of cooperative components
> Make CoEGO activity matrix more balanced

- crates/ego/examples/mopta08.rs
- crates/ego/src/solver/coego.rs
- crates/ego/src/solver/egor_solver.rs
- crates/ego/src/solver/egor_state.rs
- crates/ego/src/solver/solver_computations.rs
- crates/ego/src/solver/solver_impl.rs
- crates/ego/src/solver/solver_infill_optim.rs
- crates/ego/src/solver/trego.rs
- python/egobox/tests/test_egor.py
This PR improves optim multistart:
* Use global rng instead of sampling 
* Remove sampling from EgorState
* Take into account activity when computing multistart initial points
> Improve multistart taking into account CoEGO activity

- crates/ego/src/criteria/ei.rs
- crates/ego/src/criteria/mod.rs
- crates/ego/src/egor.rs
- crates/ego/src/solver/egor_config.rs
- crates/ego/src/types.rs
- crates/ego/src/utils/cstr_pof.rs
- python/egobox/tests/test_egor.py
- python/egobox/tests/test_gpmix.py
- python/src/egor.rs
- python/src/types.rs
This PR introduces `InfillStrategy::LOG_EI` with the straightforward naive implementation. This is experimental, the related [paper](https://openreview.net/pdf?id=1vyAG6j9PE) points numerical issues and suggest an equivalent implementation more robust.
> Add naive LogEI infill criterion implementation for experimentation
